apiVersion: v1
kind: Service
metadata:
  name: test-influx-nodeport
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9999
    nodePort: 32501
  selector:
    app.kubernetes.io/instance: test-influx
    app.kubernetes.io/name: influxdb2
  type: NodePort